#Port for Registry service
server:
  port: 8767

#Service should not register with itself
eureka:
  instance:
    hostname: eureka-server
  client:
    register-with-eureka: false
    fetch-registry: false
#    service-url:
#     defaultZone:
#      http://localhost:8767/eureka/v2/

#Managing the logging
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
